# Generated by Django 5.2.1 on 2025-05-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utilisateur",
            old_name="nom",
            new_name="nom_complet",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="prenom",
        ),
    ]
