# Generated by Django 5.2.1 on 2025-05-27 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_nom_utilisateur_nom_complet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailEchec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_echec", models.DateTimeField(auto_now_add=True)),
                ("erreur", models.TextField()),
                ("donnees", models.TextField()),
                ("resolu", models.BooleanField(default=False)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.action"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
