# Generated by Django 5.2.1 on 2025-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_emailechec"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="type",
            field=models.CharField(
                choices=[("particulier", "Particulier"), ("entreprise", "Entreprise")],
                default="particulier",
                max_length=20,
            ),
        ),
    ]
