# Generated by Django 5.2.1 on 2025-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_utilisateur_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cle",
            name="validite",
        ),
        migrations.AddField(
            model_name="produit",
            name="code_produit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="validite",
            field=models.CharField(
                choices=[
                    ("1 ans", "1 ans"),
                    ("2 ans", "2 ans"),
                    ("3 ans", "3 ans"),
                    ("a vie", "a vie"),
                ],
                default="1 ans",
                max_length=10,
            ),
        ),
    ]
