# Generated by Django 5.2.1 on 2025-06-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cle_validite_produit_code_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cle',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles', to='api.produit'),
        ),
    ]
