# Generated by Django 5.2.1 on 2025-06-07 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cle_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutique_nom', models.CharField(default='Ma Boutique', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendeurs/logos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('nombre_ventes', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('est_verifie', models.BooleanField(default=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
            },
        ),
    ]
