# Generated by Django 5.2.1 on 2025-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_vendeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
