# Generated by Django 5.2.1 on 2025-06-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_action_commentaire_action_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="status",
        ),
    ]
