# Generated by Django 5.2.1 on 2025-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_action_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="commentaire",
            field=models.CharField(default="Id transaction", max_length=100),
        ),
    ]
