# Generated by Django 5.2.1 on 2025-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_action_commentaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="avis",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
