##  Create action
POST http://localhost:8001/api/actions/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NzAyMjg0LCJpYXQiOjE3NDk2NjkxODksImp0aSI6IjA3YzdkMGQ1Zjg4NzQ3MjA4OTk3NTQxMmY0M2I3NDcyIiwidXNlcl9pZCI6MjV9.U5-_N0KgG6ia1qgxUmRegiscunp7MI-w9wWHQvzrslw

{
  "action": {
    "type": "achat",
    "prix": 500,
    "commentaire": "",
    "client": 26,
    "methode_paiement": 1
  },
  "produits": [
    {
      "produit": 2,
      "quantite": 1,
      "prix_total": 500
    }
  ]
}


### login
POST http://localhost:8001/api/token/
Content-Type: application/json

{
  "username": "test_admin",
  "password": "123"
}

### register
POST http://localhost:8001/api/signup/
Content-Type: application/json

{
  "username": "test_client",
  "password": "123",
  "nom_complet": "Romeo Client",
  "email": "romeomanoela18@gmail.com",
  "role": "client",
  "numero_telephone": "0606060606",
  "adresse": "1 rue de la paix"
}

### userInfo
GET http://localhost:8001/api/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MTMyNTI2LCJpYXQiOjE3NDg5NDgwNzgsImp0aSI6IjdkYTVhYzZiNGI1NTRiOGFiNGZjNTg1ZjIwMDJmZTVmIiwidXNlcl9pZCI6Nn0.LB-FWVK4ucReitRu3ocfBUg0apF3IQtLLa8pvhtruPs


### Update User:
PATCH http://localhost:8001/api/me/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjEwODAzLCJpYXQiOjE3NDkyMDcyMDMsImp0aSI6IjRiMTUxZDgzMDQ3YTQ0NWFhMzA2ZWQzMGE3MWUwNmJhIiwidXNlcl9pZCI6Nn0.qM_F0815CVyKZWBi2LmFTAFNDkKIY4CJK9SkXRPrX44

{
  "email": "romeomanoela@12345gmail.com",
  "password": "321"
}

### list produits
GET http://localhost:8001/api/produits/

###  approuver
POST http://localhost:8001/api/actions/39/approuver/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NzM4OTA5LCJpYXQiOjE3NDk3MzUzMDksImp0aSI6IjU1MmFiMWM0M2QzNTQ0NTQ4NGI3MDkzODgyYzkzMTY4IiwidXNlcl9pZCI6MjV9.-fX7pgubY97frYcN0nnrj7TslTwwQlv6Bp6p7dNI2vI

### actions
GET 127.0.0.1:8001/api/me/actions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NzQyNTAwLCJpYXQiOjE3NDk3Mzg5MDAsImp0aSI6ImM3OTBlMjM4YmNhMjRkYzhiOTgzZGExODc0Mzc3NDFlIiwidXNlcl9pZCI6MjV9.4PZwRfFsU1dZdMD9DblNLVrjENruBjyCBmYKw_oFB_Y