FROM python:slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Installer uv et les dépendances système
RUN apt-get update && apt-get install -y \
    build-essential curl libpq-dev \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && rm -rf /var/lib/apt/lists/*

# Ajouter le dossier de l'application
WORKDIR /app

# Copier les fichiers de configuration uv
COPY . .

# Installer uv et les dépendances Python
RUN pip install uv

# Installer les dépendances depuis uv.lock
RUN uv sync

# Exposer le port 8001
EXPOSE 8001

# Lancer Django avec le serveur de développement
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]